version: 2

sources:
#  - name: samp_data
#    database: samp_db
#    schema: dbt_schema
#    tables:
#      - name: customers

  - name: bike_data
    database: learn_db
    schema: learn_schema
    tables:
      - name: bike_tbl
